### ISSUE TITLE
any alternative links?

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [Hypverr/Railin#21]
the main one works, but just incase it gets blocked, i like to keep backups.

**Comment by Hypverr** [comment]
The only ones I currently have are:
- [railin.hypverr.xyz](https://railin.hypverr.xyz/)
- [whyshouldigoto.college](https://whyshouldigoto.college/)

However, if people are willing to host it themselves and provide domains to the community, I'm sure there will be more available.

**Comment by SuperMarioYAHOOYAHOO** [comment]
> The only ones I currently have are:
> 
> * [railin.hypverr.xyz](https://railin.hypverr.xyz/)
> * [whyshouldigoto.college](https://whyshouldigoto.college/)
> 
> However, if people are willing to host it themselves and provide domains to the community, I'm sure there will be more available.

thank you! i would deploy, but the deployment thingy i use (vercel) does not support teminal i dont think. if you make a vercel button, ill use it!

**Comment by Hypverr** [comment]
I'll try to create a deploy button for Vercel and buttons for other deployment services.

**Comment by SuperMarioYAHOOYAHOO** [comment]
> I'll try to create a deploy button for Vercel and buttons for other deployment services.

i was able to deploy it. i found some custom command settings. here's the link. (btw it was originally for doge unblocker but I found out it couldn't deploy on vercel so i repurposed the project. https://dogeforever.vercel.app/

**Comment by SuperMarioYAHOOYAHOO** [comment]
> I'll try to create a deploy button for Vercel and buttons for other deployment services.

thanks!
