### ISSUE TITLE
Hosting Railing

### ISSUE THREAD

**Issue by AaronGearheart** [hypverr/Railin#23]
What services (preferrably free) can I use to host a copy of railin games? What service do you use? I would like to host a copy or two of my own but not sure what service I should use.

**Comment by hypverr** [comment]
use railway (linked below) its free for a short time but its basically the only free option that works well. i use a random discord bot hoster because it works with JavaScript and the company that runs it doesn't care about proxy's i guess though it is paid.

https://railway.app/

**Comment by AaronGearheart** [comment]
Ultraviolet is banned on Railway

**Comment by hypverr** [comment]
ah i dont know what you should use then.
